### ISSUE TITLE
[BUG] [SERVER/EXTENSION] - TLS handshake error

### ISSUE THREAD

**Issue by electroxero** [Static-Flow/BurpSuite-Team-Extension#7] opened 2019-11-14 11:49 UTC
**Describe the bug**
When I try to connect to the team server it shows an error
 
**server**.
`TLS handshake error from 127.0.0.1:35626: tls: failed to verify client's certificate: x509: certificate has expired or is not yet valid`

**Reproduce**.
1 - Launch server : `~/go/bin/BurpSuiteTeamServer -host 127.0.0.1 -port 9999 -serverPassword test`
2 - Import .pem and .key on burp suite "Burp TC" tab.
3 - Click Connect

**Comment by Static-Flow** [comment] 2019-11-20 01:08
So I was able to connect using the setup you described above. What did you use as your connection settings in the client? 

Mine was:
Name: Tanner
Address: 127.0.0.1
Port: 9999
Password: test

Also where did you import the certs from? They should be right where you ran the server, so ~/go/bin/burpServer.X in your case.

**Comment by electroxero** [comment] 2019-11-20 13:29
Hi, I've tried another time:
![image](https://user-images.githubusercontent.com/20456461/69242737-d0dce880-0ba1-11ea-9904-0467bc808e1e.png)

The error now is changed
This is the configuration:

![image](https://user-images.githubusercontent.com/20456461/69242778-e6eaa900-0ba1-11ea-9613-0a73c7d66913.png)

Certificate and Key imported from ~/go/bin/.

**Comment by mohammed-sec2010** [comment] 2019-12-19 15:22
the BurpSuiteTeamServer worked in kali Linux only and it is not working in the ubuntu subsystem and windows 10 (go1.13.5.windows-amd64), why?

![Capture](https://user-images.githubusercontent.com/11797933/71185437-7d3ae900-228c-11ea-8843-32643ebc95b0.PNG)

**Comment by arbazkiraak** [comment] 2020-01-16 06:49
* Facing the same problem handshake error. I did everything right and according to your comment @Static-Flow

**Comment by arbazkiraak** [comment] 2020-01-16 07:03
* Burp

```
Failed to connect to server: invalid certificate or key.
Disconnected from server
Failed to connect to server: invalid certificate or key.
Disconnected from server
```

* Server

```
xxxxxxx:9999->1xxx142:44131: read: connection reset by peer
2020/01/16 12:32:03.444234 http: TLS handshake error from 1x141.1xxx42:44320: remote error: tls: unsupported extension
2020/01/16 12:32:03.615056 http: TLS handshake error from 1xxxx.141.142:43637: remote error: tls: unsupported extension
```

* Burp Extension Output log:

```
Exception occurred ...
javax.net.ssl.SSLHandshakeException: extension (5) should not be presented in certificate_request

You have been disconnected from: wss://xxxx:9999; Code: -1 

resetting room/server list

```

```
 root  ~  130   go version
go version go1.13 linux/amd64
```

https://github.com/golang/go/issues/35722

**Comment by Static-Flow** [comment] 2020-01-21 17:28
Hey everyone,

I am hard at work on this issue. I am compiling the Go server with 1.13 and the Java extension with OpenJDK 12. I am getting the "tls: unsupported extension" errors as well, though not the "extension (5)" error specifically. These errors are very opaque so finding the root cause is tough. I have tried disabling TLS 13 in both the server and the client but it didn't solve the problem. My current guess is I am generating the certificate incorrectly on the server.

**Comment by Static-Flow** [comment] 2020-01-22 18:30
Wow that took a long time to figure out for being such an easy fix. Turns out the issue is the version of Java bundled with BurpSuite. If you run the client from the command line like "java -jar ..." with a version of Java after 11.0.7 it will work fine but BurpSuite currently uses 11.0.2. I fixed it by downgrading the TLS in use by the server to TLS1.2. Please pull the new server and let me know if the issue is fixed.

**Comment by Static-Flow** [comment] 2020-01-27 12:54
I'm gonna close this issue end of day today unless someone is still having issues.

**Comment by Unwitnessed** [comment] 2020-01-28 23:36
Sorry if it is a stupid question, but where is the updated server? I installed from scratch last Friday Jan 24th and I am getting the same error.
Thx.

**Comment by Static-Flow** [comment] 2020-01-28 23:56
It's in the other repository linked in this one. Burp Suite Team Server

**Comment by arbazkiraak** [comment] 2020-01-29 12:16
* I'm still getting the same error.

compiled `https://github.com/Static-Flow/BurpSuiteTeamServer/tree/master/cmd/BurpSuiteTeamServer` 

```
→ go version
go version go1.13.6 linux/amd64
```

* Burp v2.1.07

```
2020/01/29 17:31:02.529207 http: TLS handshake error from xxxxxx: tls: faile
d to verify client's certificate: x509: certificate has expired or is not yet valid
```

**Comment by Static-Flow** [comment] 2020-01-29 12:58
That's a different error than the one this patch was for. That error message normally occurs when you are using  old certs. Compile the server, run it, and re add the certs to the Java extension.

**Comment by Unwitnessed** [comment] 2020-01-29 17:43
My problem is solved now. 

The instructions say 'go get github.com/AonCyberLabs/BurpSuiteTeamServer/cmd/BurpSuiteTeamServer', but the updated server requires 'go get github.com/Static-Flow/BurpSuiteTeamServer/cmd/BurpSuiteTeamServer/'

Thx for your help @Static-Flow, and amazing work on this extention!

**Comment by Static-Flow** [comment] 2020-01-29 17:47
Thank you for mentioning that, I have ported the code to there as well! Glad you like it!

**Closed as completed by Static-Flow** 2020-01-29 17:47 UTC
Labels: bug
